#!/usr/bin/env node
/* -*- coding: utf-8 -*-
 *
 *  server.js
 *  
 *  Author: thezero <silvethebest@yahoo.it>
 *  Start date: 26/08/2013  
 * 
 */  

var http = require("http"),
    url = require("url"),
    path = require("path"),
    fs = require("fs"),
    exec = require('child_process').exec;
    
var dir = __dirname,
	port = 8888,
	browser = "webview"
	width = 600
	height = 600;
    
if(process.argv[2] != null){ 
	var pref = require(process.argv[2]),
		dir = pref.basedir,
		port = pref.port,
		browser = pref.browser
		width = pref.width
		height = pref.height;
}

http.createServer(function(request, response) {
  	
  var req = url.parse(request.url, true)
    , method = request.method   // request method
    , query = req.query  // optional /index.html?p=somethinglikethis
    , uri = req.pathname  // request URI pathname /index.html
    , filename = path.join(dir, uri);  // request absolute filename

  if(uri == "/exit"){
    response.writeHead(418, {"Content-Type": "text/plain"});
    response.write("418 I'm a teapot - Server is Closing\n");
    response.end();
    console.log("END");
    process.exit(0);
  }

  if(method == "POST"){
	var body = '';
    request.on('data', function (data) {
      body += data;
      //console.log("Partial body: " + body);
    });
    request.on('end', function () {
	  var h = {};
	  query = url.parse(uri+"?"+body, true).query
	  if(query.redirect!=null){
        h["Location"] = "http://localhost:"+port+query.redirect;
	  }
	  console.log("{\"method\":\""+method+"\",\"uri\":\""+uri+"\",\"serial\":\""+body+"\",\"json\":"+JSON.stringify(query, null, 0)+"}");
	  h["Content-Type"] = "text/plain";
      response.writeHead(301, h);
	  response.write("Request Sent\n");
      response.end();
      return;
    });  
  }

  var contentTypesByExtension = {
    '.html': "text/html",
    '.css':  "text/css",
    '.js':   "text/javascript"
  };

  fs.exists(filename, function(exists) {
    if(!exists) {
      response.writeHead(404, {"Content-Type": "text/plain"});
      response.write("404 Not Found\n");
      response.end();
      return;
    }

    if (fs.statSync(filename).isDirectory()) filename += '/index.html';

    fs.readFile(filename, "binary", function(err, file) {
      if(err) {        
        response.writeHead(500, {"Content-Type": "text/plain"});
        response.write(err + "\n");
        response.end();
        return;
      }

      var headers = {};
      var contentType = contentTypesByExtension[path.extname(filename)] || 'text/plain';
      if (contentType) headers["Content-Type"] = contentType;
      response.writeHead(200, headers);
      response.write(file, "binary");
      response.end();
    });
  });
}).listen(parseInt(port, 10));

console.log("# Fuku is running at\n#  => http://localhost:" + port + "/\n# CTRL + C to shutdown");

if(browser == "null" || browser == "default"){
  if(process.platform == "win32") { 
	exec("start http://localhost:" + port);
  } else if(process.platform == "darwin") { 
	exec("open http://localhost:" + port);
  } else if(process.platform == "linux") { 
    exec("x-www-browser http://localhost:" + port);
  }
} else if(browser == "webview" || browser == "pywebview"){
  if(fs.existsSync(__dirname+"/pywebview")){
    exec(__dirname+"/pywebview http://localhost:" + port + " "+width+" "+height);
  } else {
    exec(__dirname+"/pywebview.py http://localhost:" + port + " "+width+" "+height);
  }
} else {
  exec(browser+" http://localhost:"+port);
}
